part of 'home_bloc.dart';

@freezed
class HomeState with _$HomeState {
  const factory HomeState({
    required int carouselIndex,
    required bool isCarouselLoading,
    required bool isCarouselError,
    required List<TMDBResponse> carouselList,
    required bool isTopTvError,
    required bool isTopMovieError,
    required bool isTopTvLoading,
    required bool isTopMovieLoading,
    required List<TMDBResponse> topTvList,
    required List<TMDBResponse> topMovieList,
    required List<TMDBResponse> topRatedTv,
    required List<TMDBResponse> topRatedMovies,
    required bool isTopRatedMovieError,
    required bool isTopRatedTvError,
    required bool isTopRatedMovieLoading,
    required bool isTopRatedTvLoading,
    required List<TMDBResponse> genreResult1,
    required bool isGenreLoading1,
    required bool isGenreError1,
    required List<TMDBResponse> genreResult2,
    required bool isGenreLoading2,
    required bool isGenreError2,
    required List<TMDBResponse> genreResult3,
    required bool isGenreLoading3,
    required bool isGenreError3,
    required List<TMDBResponse> genreResult4,
    required bool isGenreLoading4,
    required bool isGenreError4,
    required List<String> genreNames,
    required List<int> genreIds,
  }) = _HomeState;
  factory HomeState.initial() => const HomeState(
        carouselIndex: 0,
        isCarouselLoading: false,
        isCarouselError: false,
        carouselList: [],
        isTopTvError: false,
        isTopMovieError: false,
        isTopMovieLoading: false,
        isTopTvLoading: false,
        topMovieList: [],
        topTvList: [],
        isTopRatedMovieError: false,
        isTopRatedMovieLoading: false,
        isTopRatedTvError: false,
        isTopRatedTvLoading: false,
        topRatedMovies: [],
        topRatedTv: [],
        genreResult1: [],
        isGenreLoading1: false,
        isGenreError1: false,
        genreResult2: [],
        isGenreLoading2: false,
        isGenreError2: false,
        genreResult3: [],
        isGenreLoading3: false,
        isGenreError3: false,
        genreResult4: [],
        isGenreLoading4: false,
        isGenreError4: false,
        genreNames: ['','','',''],
        genreIds: []
      );
}
